name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
  - type: input
    id: version
    attributes:
      label: Version / commit SHA
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
